spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    #In memory config -> jdbc:h2:mem:testdb In order to connect form IDEA you need to use direct path
    url: jdbc:h2:file:./database/dev;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: username
    password: password