--liquibase formatted sql

--changeset author:id1

CREATE TABLE COUNTRY
(
    ID           BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR,
    COUNTRY_CODE VARCHAR
);

CREATE TABLE FOLDER
(
    ID           BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR
);

CREATE TABLE DOCUMENT
(
    ID           BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ISSUER       VARCHAR ,
    NAME         VARCHAR,
    CREATE_DATE  TIMESTAMP,
    UPDATE_DATE  TIMESTAMP,
    UPLOAD_DATE  TIMESTAMP,
    FILE_CONTENT BLOB,
    COUNTRY BIGINT, FOREIGN KEY (COUNTRY) REFERENCES COUNTRY,
    FOLDER BIGINT, FOREIGN KEY (FOLDER) REFERENCES FOLDER
);

CREATE TABLE TAGS
(
    ID           BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TAG          VARCHAR,
    DOCUMENT BIGINT , FOREIGN KEY (DOCUMENT) REFERENCES DOCUMENT
);

ALTER TABLE DOCUMENT ADD COLUMN TAGS BIGINT REFERENCES  TAGS;

